apiVersion: edgecore.config.kubeedge.io/v1alpha1
database:
  dataSource: /var/lib/kubeedge/edgecore.db
kind: EdgeCore
modules:
  edgeHub:
    heartbeat: 15
    httpServer: https://172.25.23.194:10002
    token: fdbfbfd9a5317389e5b68bd1579fa3701780890be129520e2b7a269fbfdf3a61.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzQ4MTY4MTR9.AJt0x2J4iKxJlImV1vWJ7d_Fne_vOikzUNK6JUGEfgk
    websocket:
      enable: true
      handshakeTimeout: 30
      readDeadline: 15
      server: 172.25.23.194:10000
      writeDeadline: 15
    tlsCaFile: /etc/kubeedge/ca/rootCA.crt
    tlsCertFile: /etc/kubeedge/certs/server.crt
    tlsPrivateKeyFile: /etc/kubeedge/certs/server.key
  edged:
    cgroupDriver: cgroupfs
    cgroupRoot: ""
    cgroupsPerQOS: true
    clusterDNS: ""
    clusterDomain: ""
    devicePluginEnabled: false
    dockerAddress: unix:///var/run/docker.sock
    gpuPluginEnabled: false
    hostnameOverride: node193-ctr.kedge
    nodeIP: 172.0.0.1 #193
    podSandboxImage: registry.cn-shenzhen.aliyuncs.com/infrasync/rancher-pause:3.2
    remoteImageEndpoint: unix:///run/containerd/containerd.sock
    remoteRuntimeEndpoint: unix:///run/containerd/containerd.sock
    runtimeType: containerd #docker
  eventBus:
    mqttMode: 2
    mqttQOS: 0
    mqttRetain: false
    mqttServerExternal: tcp://127.0.0.1:1883
    mqttServerInternal: tcp://127.0.0.1:1884

  edgeStream:
    enable: true
    handshakeTimeout: 30
    readDeadline: 15
    server: 172.25.23.194:10004
    tlsTunnelCAFile: /etc/kubeedge/ca/rootCA.crt
    tlsTunnelCertFile: /etc/kubeedge/certs/server.crt
    tlsTunnelPrivateKeyFile: /etc/kubeedge/certs/server.key
    writeDeadline: 15